language: php
php:
- 5.5
- 5.6
- 7.0
- 7.1
- 7.2
sudo: false
before_script:
- composer self-update
- composer install --prefer-dist --no-interaction
before_install:
- openssl aes-256-cbc -K $encrypted_e44c58426490_key -iv $encrypted_e44c58426490_iv
  -in XRay-67d8fdd0bba3.json.enc -out XRay-67d8fdd0bba3.json -d
- cp config.production.php config.php
deploy:
  skip_cleanup: true
  provider: gae
  default: true
  project: xray-p3k-io
  on:
    branch: master
    php: 5.5
  keyfile: XRay-67d8fdd0bba3.json
